services:
  - name: mabrix-backend
    type: web
    env: node
    plan: free
    buildCommand: yarn
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: CHANGE_ME
      - key: FRONTEND_URL
        value: https://portfolio-backend-jwm1.onrender.com
